<ul class="filtermenumap">
    <li><a href="#" title="Filter Map based on Health Topics or Human Rights" style="cursor:default;background-color:white;color:#900;"><b>Filtra el Mapa &raquo;</b></a></li>
    <li><a href="javascript:void(0);" id="id_ht"  onMouseOut="mouseOutHander();" onMouseover="fadeIn('id_healthtopics');"  ><span><b>Temas de Salud</b></span></a>


        <ul class='filtermenumapm' id="id_healthtopics" style="width:850px;display:none;" onMouseOut="mouseOutHander('id_healthtopics');">
            
            <li><a href="javascript:void(0);" onClick="loadmap('Water, sanitation and hygiene', '115', 'HT');">Agua, saneamiento e higiene</a></li>   
            <li><a href="javascript:void(0);" onClick="loadmap('Hospitals', '114', 'HT');">Hospitales</a></li>    
            <li><a href="javascript:void(0);" onClick="loadmap('Occupational health', '122', 'HT');">Salud ocupacional</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Informed consent', '118', 'HT');">Consentimiento informado</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Health information', '196', 'HT');">Información de salud</a></li>            
            <li><a href="javascript:void(0);" onClick="loadmap('Sexual and reproductive health', '124', 'HT');">Salud sexual y reproductiva</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Health care and health services', '104', 'HT');">Cuidado y servicios de salud</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Medical malpractice', '119', 'HT');">Malpraxis médica</a></li>            
            <li><a href="javascript:void(0);" onClick="loadmap('Public safety', '202', 'HT');">Seguridad pública</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Disasters and emergencies', '199', 'HT');">Desastres y emergencias</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Medicines', '105', 'HT');">Medicines</a></li> 
            <li><a href="javascript:void(0);" onClick="loadmap('Health systems and financing', '112', 'HT');">Sistemas de salud y financiamiento</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Disabilities', '198', 'HT');">Discapacidades</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Poverty', '123', 'HT');">Pobreza</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Controlled substances', '116', 'HT');">Sustancias controladas</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Diet and nutrition', '110', 'HT');">Dieta y nutrición </a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Prisons', '201', 'HT');">Prisiones</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Tobacco', '126', 'HT');">Tabaco</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Chronic and noncommunicable diseases', '107', 'HT');">Enfermedades crónicas y no transmisibles</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Environmental health', '109', 'HT');">Salud ambiental</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('HIV/AIDS', '113', 'HT');">VIH/SIDA</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Infectious diseases', '117', 'HT');">Enfermedades infecciosas</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Child and adolescent health', '106', 'HT');">Salud del niño y los adolescentes</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Violence', '125', 'HT');">Violencia</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Aging', '203', 'HT');">Envejecimiento</a></li>      
            
            <li><a href="javascript:void(0);" onClick="loadmap('Mental health', '120', 'HT');">Salud mental</a></li>
        </ul>
    </li>

    <li><a href="javascript:void(0);" id="id_hr" onMouseOut="mouseOutHander();" onMouseover="fadeIn('id_humanrights');" ><span><b>Derechos Humanos</b></span></a>
        <ul class='filtermenumapm' id="id_humanrights" style="width:850px;display:none;" onMouseOut="mouseOutHander('id_humanrights');">

            <li><a href="javascript:void(0);" onClick="loadmap('Right to food', '134', 'HR');">Derecho a la alimentación</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to health', '135', 'HR');">Derecho a la salud</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to development', '215', 'HR');">Derecho al desarrollo</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Right to education', '131', 'HR');">Derecho a la educación</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to social security', '140', 'HR');">Derecho a la seguridad social</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to favorable working conditions', '132', 'HR');">Derecho al goce de condiciones de <br>trabajo favorables</a></li>
           
            <li><a href="javascript:void(0);" onClick="loadmap('Right to bodily integrity', '130', 'HR');">Derecho a la integridad física</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to life', '138', 'HR');">Derecho a la vida</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to work', '142', 'HR');">Derecho al trabajo</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Right to liberty and security of person', '137', 'HR');">Derecho a la libertad y a la seguridad<br> personal</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to family life', '133', 'HR');">Derecho a la vida familiar</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Freedom from torture', '208', 'HR');">Derecho contra la tortura y el trato cruel,<br> inhumano o degradante</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Right to acquire nationality', '214', 'HR');">Derecho a la nacionalidad</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to housing', '136', 'HR');">Derecho a la vivienda</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right of access to information', '213', 'HR');">Derecho del acceso a la información</a></li> 
            
            <li><a href="javascript:void(0);" onClick="loadmap('Freedom from discrimination', '127', 'HR');">Derecho a la no discriminación</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Rights to the benefits of culture', '219', 'HR');">Derecho a los beneficios de la cultura</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Freedom of association', '209', 'HR');">Libertad de asociación</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Right to participation', '217', 'HR');">Derecho a la participación</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to a clean environment', '129', 'HR');">Derecho a un medio ambiente sano</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Freedom of expression', '210', 'HR');">Libertad de expresión</a></li>
            
            <li><a href="javascript:void(0);" onClick="loadmap('Right to privacy', '139', 'HR');">Derecho a la privacidad</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Right to water and sanitation', '141', 'HR');">Derecho al agua y al saneamiento</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Freedom of movement and residence', '211', 'HR');">Libertad de movimiento y residencia</a></li>
           
            <li><a href="javascript:void(0);" onClick="loadmap('Right to property','218', 'HR');">Derecho a la propiedad</a></li>  
            <li><a href="javascript:void(0);" onClick="loadmap('Right to due process/fair trial', '216', 'HR');">Derecho al debido proceso/juicio justo</a></li>
            <li><a href="javascript:void(0);" onClick="loadmap('Freedom of religion', '212', 'HR');">Libertad de religión</a></li>

        </ul>

    </li>
    

    <div id="category_label" ></div>

</ul>
