<ul class="filtermenumap">
<li><a href="#" title="Filter Map based on Health Topics or Human Rights" style="cursor:default;background-color:white;color:#900;"><b>Filter Map &raquo;</b></a></li>
  <li><a href="javascript:void(0);" id="id_ht"  onMouseOut="mouseOutHander();" onMouseover="fadeIn('id_healthtopics');"  ><span><b>Health Topics</b></span></a>


    <ul class='filtermenumapm' id="id_healthtopics" style="width:850px;display:none;" onMouseOut="mouseOutHander('id_healthtopics');">

<!--<li><a href="javascript:void(0);" onClick="loadmap('Aging','203');"><input type="checkbox" name="vehicle" width="10px;"  text="abc">Aging</input></a></li>-->
<li><a href="javascript:void(0);" onClick="loadmap('Aging','203','HT');">Aging</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Health information','196','HT');">Health information</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Occupational health','122','HT');">Occupational health</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Child and adolescent health','106','HT');">Child and adolescent health</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Health systems and financing','112','HT');">Health systems and financing</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Poverty','123','HT');">Poverty</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Chronic and noncommunicable diseases','107','HT');">Chronic and noncommunicable diseases</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('HIV/AIDS','113','HT');">HIV/AIDS</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Prisons','201','HT');">Prisons</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Controlled substances','116','HT');">Controlled substances</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Hospitals','114','HT');">Hospitals</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Public safety','202','HT');">Public safety</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Diet and nutrition','110','HT');">Diet and nutrition</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Infectious diseases','117','HT');">Infectious diseases</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Sexual and reproductive health','124','HT');">Sexual and reproductive health</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Disabilities','198','HT');">Disabilities</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Informed consent','118','HT');">Informed consent</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Tobacco','126','HT');">Tobacco</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Disasters and emergencies','199','HT');">Disasters and emergencies</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Medical malpractice','119','HT');">Medical malpractice</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Violence','125','HT');">Violence</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Environmental health','109','HT');">Environmental health</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Medicines','105','HT');">Medicines</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Water, sanitation and hygiene','115','HT');">Water, sanitation and hygiene</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Health care and health services','104','HT');">Health care and health services</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Mental health','120','HT');">Mental health</a></li>




    </ul>
</li>

  <li><a href="javascript:void(0);" id="id_hr" onMouseOut="mouseOutHander();" onMouseover="fadeIn('id_humanrights');" ><span><b>Human Rights</b></span></a>
<ul class='filtermenumapm' id="id_humanrights" style="width:850px;display:none;" onMouseOut="mouseOutHander('id_humanrights');">

<li><a href="javascript:void(0);" onClick="loadmap('Freedom from discrimination','127','HR');">Freedom from discrimination</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to bodily integrity','130','HR');">Right to bodily integrity</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to liberty and security of person','137','HR');">Right to liberty and security of person</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Freedom from torture','208','HR');">Freedom from torture</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to development','215','HR');">Right to development</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to life','138','HR');">Right to life</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Freedom of association','209','HR');">Freedom of association</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to due process/fair trial','216','HR');">Right to due process/fair trial</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to participation','217','HR');">Right to participation</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Freedom of expression','210','HR');">Freedom of expression</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to education','131','HR');">Right to education</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to privacy','139','HR');">Right to privacy</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Freedom of movement and residence','211','HR');">Freedom of movement and residence</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to family life','133','HR');">Right to family life</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to property','218','HR');">Right to property</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Freedom of religion','212','HR');">Freedom of religion</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to favorable working conditions','132','HR');">Right to favorable working conditions</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to social security','140','HR');">Right to social security</a></li>


<li><a href="javascript:void(0);" onClick="loadmap('Right of access to information','213','HR');">Right of access to information</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to food','134','HR');">Right to food</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to water and sanitation','141','HR');">Right to water and sanitation</a></li>


<li><a href="javascript:void(0);" onClick="loadmap('Right to a clean environment','129','HR');">Right to a clean environment </a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to health','135','HR');">Right to health</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to work','142','HR');">Right to work</a></li>

<li><a href="javascript:void(0);" onClick="loadmap('Right to acquire nationality','214','HR');">Right to acquire nationality</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Right to housing','136','HR');">Right to housing</a></li>
<li><a href="javascript:void(0);" onClick="loadmap('Rights to the benefits of culture','219','HR');">Rights to the benefits of culture</a></li>

    </ul>

</li>

<div id="category_label" ></div>

</ul>
